# permissions for end users to view configmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configmap-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pg-operator
    app.kubernetes.io/part-of: pg-operator
    app.kubernetes.io/managed-by: kustomize
  name: configmap-viewer-role
rules:
- apiGroups:
  - configmaps.example.com
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configmaps.example.com
  resources:
  - configmaps/status
  verbs:
  - get
