---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - configmaps.example.com
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configmaps.example.com
  resources:
  - configmaps/finalizers
  verbs:
  - update
- apiGroups:
  - configmaps.example.com
  resources:
  - configmaps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.example.com
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.example.com
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.example.com
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - secrets.example.com
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.example.com
  resources:
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.example.com
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.example.com
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.example.com
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - services.example.com
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
