apiVersion: v1
kind: Namespace
metadata:
  name: pg-test
  labels:
    name: pg-test
---
apiVersion: deployments.example.com/v1alpha1
kind: Deployment
metadata:
  name: pg-deploy
  namespace: pg-test
spec:
  cpu_lim: "200m"
  cpu_req: "100m"
  mem_lim: "256Mi"
  mem_req: "128Mi"
  pg_version: "14"
  port: 5432
---
apiVersion: secrets.example.com/v1alpha1
kind: Secret
metadata:
  name: pg-secret
  namespace: pg-test
spec:
  database: test
  user: test
---
apiVersion: configmaps.example.com/v1alpha1
kind: ConfigMap
metadata:
  name: pg-cm
  namespace: pg-test
spec:
  pgConf:
     maxConnections: 100
     port: 5432
---
apiVersion: services.example.com/v1alpha1
kind: Service
metadata:
  name: pg-service
  namespace: pg-test
spec:
  ports:
    - port: 5432


