apiVersion: secrets.example.com/v1alpha1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: secret
    app.kubernetes.io/instance: secret-sample
    app.kubernetes.io/part-of: pg-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pg-operator
  name: secret-sample
spec:
  # TODO(user): Add fields here
